### ISSUE TITLE
Cstring in busmaster

### ISSUE THREAD

**Issue by liguangcheng** [rbei-etas/busmaster#516]
I found a sentence "Substancial parts of the file must be replaced to eliminate errors which creep in while using CString" which is in development document PDF file. what dase it mean? I can not understand .anyone who can help me!

**Comment by tolstiybh** [comment]
Hello.

Currently I am working on the Visual Studio 2013 ultimate. I had tried to compile the solution, however I received the error regarding cstringt.h library. Then I followed recommendations concerning the WinDDK patch, but when I launched this patch, it got a notification: "patch" is not external or internal command of the running programor package file. For the continue press any key.
I assume that patch's changes hadn't been applied. Therefore, what this notification mean and what should I do in order to properly execute this patch? 

Thanks in advance)
